import { useState } from "react";
import { ChevronDown } from "lucide-react";
import AnimatedSection from "./AnimatedSection";

const faqs = [
  {
    q: "What types of QR codes can I create with QR Studio?",
    a: "QR Studio supports URLs, vCards, WiFi networks, plain text, email, phone numbers, SMS, geographic locations, and social media profiles. Each type has a dedicated input form optimized for that content.",
  },
  {
    q: "Is QR Studio really free to use?",
    a: "Yes! You can generate, customize, and download unlimited static QR codes completely free — no signup required. Premium plans unlock dynamic QR codes, scan analytics, white labeling, and advanced branding features.",
  },
  {
    q: "Can I add my logo to a QR code?",
    a: "Absolutely. Upload any logo or image and QR Studio will embed it in the center of your QR code while maintaining scannability. You can adjust size, padding, and background behind the logo.",
  },
  {
    q: "What download formats are available?",
    a: "Export your QR codes in PNG, WEBP, or JPG format at high resolution (up to 2048×2048 pixels). All downloads are print-ready and suitable for business cards, flyers, posters, and digital use.",
  },
  {
    q: "Do you offer QR code scan analytics?",
    a: "Premium users get real-time scan analytics including total scans, unique visitors, geographic heatmaps, device & browser breakdown, referrer tracking, and time-based scan patterns.",
  },
  {
    q: "What is white labeling and how does it work?",
    a: "White labeling lets you remove QR Studio branding and replace it with your own. Use your custom domain for redirect URLs, add your logo watermark, and create a fully branded QR code experience for your clients.",
  },
  {
    q: "Are QR codes generated by QR Studio scannable by all devices?",
    a: "Yes. All QR codes follow the ISO/IEC 18004 standard and are scannable by every modern smartphone camera, QR scanner app, and barcode reader. We include error correction to ensure reliability even when partially obscured.",
  },
  {
    q: "Can I track how many times my QR code is scanned?",
    a: "With a premium plan, every scan is logged with timestamp, location, device type, and referrer data. View trends over time, compare QR codes side-by-side, and export reports for your marketing campaigns.",
  },
];

const FAQSection = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section id="faq" className="py-12 md:py-16 lg:py-20 bg-muted/20 border-y border-border/50" aria-label="Frequently Asked Questions">
      <div className="container mx-auto px-4 lg:px-8 max-w-3xl">
        <AnimatedSection>
          <div className="text-center mb-8 md:mb-10">
            <h2 className="text-xl md:text-2xl lg:text-3xl font-semibold tracking-tight mb-2">
              Frequently Asked Questions
            </h2>
            <p className="text-xs md:text-sm text-muted-foreground max-w-md mx-auto">
              Everything you need to know about creating and managing QR codes with QR Studio.
            </p>
          </div>
        </AnimatedSection>

        <AnimatedSection delay={100}>
          <div className="space-y-2">
            {faqs.map((faq, i) => (
              <div
                key={i}
                className="border border-border/60 rounded-lg bg-background/50 overflow-hidden transition-colors hover:border-primary/30"
              >
                <button
                  onClick={() => setOpenIndex(openIndex === i ? null : i)}
                  className="w-full flex items-center justify-between px-4 py-3 text-left text-sm font-medium text-foreground"
                  aria-expanded={openIndex === i}
                >
                  <span>{faq.q}</span>
                  <ChevronDown
                    className={`h-4 w-4 shrink-0 ml-2 text-muted-foreground transition-transform duration-300 ease-out ${
                      openIndex === i ? "rotate-180" : ""
                    }`}
                  />
                </button>
                <div
                  className={`grid transition-all duration-300 ease-out ${
                    openIndex === i ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"
                  }`}
                >
                  <div className="overflow-hidden">
                    <div className="px-4 pb-3 text-xs text-muted-foreground leading-relaxed">
                      {faq.a}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </AnimatedSection>
      </div>
    </section>
  );
};

export default FAQSection;
